name: "Check CVEs"

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-cves:
    runs-on: ubuntu-latest

    steps:
    - name: Check out codebase
      uses: actions/checkout@v4

    - name: Scan current project
      uses: anchore/scan-action@v3
      with:
        path: "."