name: "Check CVEs"

on:
  workflow_dispatch:
  push:

jobs:
  check-cves:
    runs-on: ubuntu-latest

    steps:
    - name: Check out codebase
      uses: actions/checkout@v4
    
    - name: Debug
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: env | sort
    
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: .
        upload-artifact: true
        format: spdx-json
        github-token: ${{ env.GITHUB_TOKEN }}
        output-file: "cf-cli-sbom.spdx.json"
    
    - name: Debug
      run: pwd && ls -latr . && cat "cf-cli-sbom.spdx.json"